/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.salsapop

import spock.lang.Specification

class ValidateCalendarTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new ValidateCalendar()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
